### PR TITLE
WIP: Merges the master branch of mars

### PR DESCRIPTION
**Pull request by Rauldg**
@annaborn This merge into the envire branch is somehow wrong.

Did you actually start working from the branch `envire`? 

Do we still need the branch envire of this repo at all or should we just use from now on the envire_2020?

### CODE REVIEW

**Comment by annaborn** [comment]
@Rauldg: Yes, the envire_2020 is based on envire branch. 
I would leave the branch envire_2020, since we are planning to move to other repo.

**Comment by annaborn** [comment]
@Rauldg : yes , the envire_2020 is based on envire branch. 
I would keep both branches, maybe someone uses the envire branch

**Comment by Rauldg** [comment]
> I would keep both branches, maybe someone uses the envire branch

We are the only ones using the envire branch and is not maintained. This MR will integrate into it the changes from envire-2020, why keeping then envire-2020 after the merge?

**Comment by Rauldg** [comment]
What is not clear for me is why there are so many commits in the MR, didn't we make any update on the envire branch since march 2018?

**Comment by annaborn** [comment]
> > I would keep both branches, maybe someone uses the envire branch
> 
> We are the only ones using the envire branch and is not maintained. This MR will integrate into it the changes from envire-2020, why keeping then envire-2020 after the merge?

If nobody else uses it, we can merge both branches and keel envire only

**Comment by annaborn** [comment]
> What is not clear to me is why there are so many commits in the MR, didn't we make any update on the envire branch since march 2018?



> What is not clear to me is why there are so many commits in the MR, didn't we make any update on the envire branch since march 2018?

How I know, after I left, nobody worked on the envire-mars-merge anymore.
So there are commits in mars from march 2018

**Pull request merged**
